### ISSUE TITLE
hardcoded http links to JS.

### ISSUE THREAD

**Issue by danmarsden** [jsxgraph/moodle-filter_jsxgraph#10]
Sites that use fulltime ssl (most sites should be doing this now) will not work when a jsxgraph serverversion is defined in the settings.

I'm not clear why this is actually required though - couldn't the settings to use an external js lib be completely removed and always just use the included js within the plugin?

**Comment by walterandreas** [comment]
Before this version of our filter was submitted, it was significantly expanded and improved. As part of these enhancements, a request from users was that they could easily change the included JSX version via the admin menu without overwriting the jsxgraphcore.js file. Since we can not supply all our old versions of JSXGraph with the filter, it is necessary to include "old" or other versions from cloudfare server (except version 0.99.5, which unfortunately only exists on our own servers).

I have changed the protocol in the code to https. Now the integration on a http and a https-moodle-installations should work.

**Comment by walterandreas** [comment]
It is now a setting for the administrator, whether a server version is included via http or https
