### ISSUE TITLE
UTF-8 character encoding

### ISSUE THREAD

**Issue by anieminen** [jsxgraph/moodle-filter_jsxgraph#13]
Hello,

It seems that the JSXGraph filter is not handling UTF-8 characters correctly in quiz questions. Scandinavian å, ä or ö letters are all garbled in the example below. If I disable the filter, the characters are displayed correctly. 

![finnish_quiz](https://user-images.githubusercontent.com/15781654/60420114-98873e80-9bef-11e9-9d8a-8ea7c4231f21.PNG)

I can see that `mb_convert_encoding` function has been used in the code but those lines are commented out for some reason (https://github.com/jsxgraph/moodle-filter_jsxgraph/blob/master/filter.php#L90). 

I am using Moodle 3.5.6 & the latest version of the filter.

**Comment by nadavkav** [comment]
I am experiencing the same issue for Hebrew content, on latest stable Moodle 3.7

**Comment by nadavkav** [comment]
Here is a fix: https://stackoverflow.com/a/8218649/374316

**Comment by walterandreas** [comment]
Hello, 
thank you for your interest! I will take care of the problem after my exams and hope to come up with a solution towards the end of August. 
Andreas

**Comment by nadavkav** [comment]
@walterandreas good luck with the exams!
Here is the quick fix that worked for me:
`$dom->loadHTML('<?xml encoding="utf-8" ?>' .$html);`

**Comment by walterandreas** [comment]
Hello.

At the moment I have a small bridge in the calendar so I was able to take care of the problem.

Some time ago I completely reprogrammed the plugin. Unfortunately, I can not remember exactly why I commented out the lines with converting. Actually, this error should have occurred earlier (we have in German ä ö and ü too).

Because I dont know if commenting out did not have a good reason (maybe a complication with another filter), let's continue with the following workaround: I've added a setting for administrators to set >code>mb_convert_encoding</code> to run or not.

I'm about to push a new version of the filter in GitHub and commit a new Moodle version. Please test the functionality and get in touch again if problems still occur.

Best regards,
Andreas
