### ISSUE TITLE
using the filter with STACK

### ISSUE THREAD

**Issue by raedshorrosh** [jsxgraph/moodle-filter_jsxgraph#28]
I have tried using the filter within a STACK question in Moodle and it works fine.  However, I get JS error in the editing quiz mode.  The error disables Moodle from deleting a question in the quiz and disables the ability to reorder the questions.  When I preview the question, it works fine without any error.  The source of the error is the embedded variable notation {#a_variable#} or {@a_variable@} used in STACK. This problem does not occur when I use jsxgraph filter of STACK. I wanted to use your filter since it supports the latest version of jsxgraph, but with this error it is impossible to use with STACK.  The STACK filter for jsxgraph that is shipped with STACK works fine, but it only supports old version of jsxgraph.

![image](https://user-images.githubusercontent.com/90145979/167426202-8ba4145e-0a40-4cf2-9ad7-8c9af54da96e.png)

**Comment by andreas-web** [comment]
Dear raedshorrosh,

unfortunately this is a known problem. It is not possible to use our filter in STACK because they are not compatible with each other. You must use the plugin built into STACK.
We only have influence on the development of JSXGraph and the project moodle-filter_jsxgraph, but we have NO influence on STACK and the version of JSXGraph used in it.
Please ask STACK if they can update to the latest version of JSXGraph.

Best regards,
Andreas
